name: keepital
description: for money for life.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  currency_picker: ^2.0.3
  dotted_line: ^3.1.0
  enum_to_string: ^2.0.1
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^3.5.2
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.1.0
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.1.1
  intl: ^0.17.0
  math_expressions: ^2.2.0
  modal_bottom_sheet: ^2.0.0
  money_formatter: ^0.0.3
  pull_to_refresh: ^2.0.0
  tuple: ^2.0.0
  chips_choice: ^2.0.1

dev_dependencies:
  build_runner: null
  change_app_package_name: ^1.0.0
  flutter_gen: ^4.1.0
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/in_app_icon/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#242526"
  image: "assets/images/keepital_logo.png"

flutter_gen:
  output: lib/app/core/values
  line_length: 250
  integrations:
    flutter_svg: true
  assets:
    package_parameter_enabled: false
    style: camel-case
